/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.tienda.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.tienda.model.JsonApiBodyRequest;
import co.tienda.model.JsonApiBodyResponseErrors;
import co.tienda.model.JsonApiBodyResponseSuccess;
import co.tienda.model.Producto;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-13T11:30:22.608-05:00")

@Api(value = "producto", description = "the Product API")
public interface ProductApi {
    
    @ApiOperation(value = "Find all productos", nickname = "findAll", notes = "Seleccionar todos los productos", response = List.class, tags={ "resolve-enigma-api-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = List.class),
        @ApiResponse(code = 400, message = "Invalid status value") })
    @RequestMapping(value = "/producto",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> findAll();
    
    @ApiOperation(value = "Agregar producto", nickname = "addProducto", notes = "", tags={ "resolve-enigma-api-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 400, message = "Bad request") })
    @RequestMapping(value = "/producto",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<?> addProducto(@ApiParam(value = "Producto" ,required=true )  @Valid @RequestBody Producto body);
}
